#!/bin/bash
mv /opt/HBmonitor/lastheard.log /opt/HBmonitor/lastheard.log.save
/usr/bin/tail -150 /opt/HBmonitor/lastheard.log.save > /opt/HBmonitor/lastheard.log
mv /opt/HBmonitor/lastheard.log /var/www/html/lastheard.log.save
/usr/bin/tail -150 /opt/HBmonitor/lastheard.log.save > /opt/HBmonitor/lastheard.log
